name: talk_s3_2017
channels:
- damianavila82
- conda-forge
- anaconda-fusion
- defaults
dependencies:
- bokeh
- ipywidgets
- jupyter
- matplotlib
- notebook
- numpy
- pandas
- python=3.6
- scikit-learn
- scipy
- tqdm
- rise

